targets:
  $default:
    builders:
      di_generator_build|di_generator:
        enabled: true
        generate_for:
          - lib/**
          - test/**

builders:
  di_generator:
    import: "package:di_generator_build/builder.dart"
    builder_factories: ["buildDiGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
