name: example
description: Example usage of di_generator_build package
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  di_generator_build:
    path: ../
  get_it: ^8.2.0

dev_dependencies:
  build_runner: ^2.7.0
  build_test: ^3.3.2
  test: ^1.26.3
