name: example
description: Example usage of di_generator_build package
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  di_generator_build:
    path: ../
  get_it: ^7.6.0

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.1.0
  test: ^1.24.0
