name: di_generator_build
description: A powerful build runner package for automatic dependency injection code generation using GetIt in Flutter applications.
version: 1.6.1

homepage: https://github.com/sumitnemade/di_generator_build
repository: https://github.com/sumitnemade/di_generator_build
issue_tracker: https://github.com/sumitnemade/di_generator_build/issues

documentation: https://github.com/sumitnemade/di_generator_build#readme

# Add topics for better discoverability (max 5 allowed by pub.dev)
topics:
  - dependency-injection
  - code-generation
  - build-runner
  - getit
  - flutter

# Add keywords for search
keywords:
  - dependency injection
  - code generation
  - build runner
  - getit
  - flutter
  - dart
  - auto-register
  - di

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^8.1.1
  build: ^3.0.2
  get_it: ^8.2.0
  source_gen: ^3.1.0

dev_dependencies:
  build_runner: ^2.7.0
  build_test: ^3.3.2
  lints: ^6.0.0
  test: ^1.26.3

# Remove the flutter section as this is not a Flutter package
# This is a build_runner package that works with Flutter projects
